name: quotes_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.14
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  reusable_components:
    git:
      url: https://github.com/ahmedghaly15/Reusable-Components-Package
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200

flutter_assets:
  assets_path: assets/images/
  output_path: lib/src/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
